### ISSUE TITLE
Empty results in the lasso_mosek

### ISSUE THREAD

**Issue by ds2010** [zhan-gao/convex_prog_in_econometrics#1]
Hi Zhan Gao,

I was trying to run the lasso_mosek.R, but the final estimates a (i.e., ahat) and b (i.e., bhat) are empty. Is there any way you could check and fix that? I am not familiar with the MOSEK in R and I failed to debug it. 

There is one more question: why did you use the formula `log(p+1)/sqrt(n)` to determine the lambda here? It seems that it is different from the paper `Koenker and Mizera 2014`, JSS.  Thanks for your great work.

Best wishes,
Sheng

**Comment by zhan-gao** [comment]
Hi Sheng,

Thank you very much for your interest in this work. 

For your first question, the problem is line 51. I updated the grammar of this line to be compatible with the latest version of Mosek, and now it should work.

For the tuning parameter, the rate of lambda should be sqrt(log(p)/n) according to theory. You may check Buhlmann and van de Geer (2011) for details. Here we are just trying to illustrate the numerical scheme, so I let lambda equal 0.25 to avoid confusion. In practice, parameter tuning is necessary.
